
# Configuration:
web:
  image: eeacms/shibboleth-idp:latest
  ports:
  - 8080:8080
  volumes:
  - shibboleth-idp:/opt/shibboleth-idp
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=prodI-cph-02

