
# Configuration:
# Hostname: idpnt.eea.europa.eu
web:
  image: eeacms/shibboleth-idp:latest
  ports:
  - 443:4443
  - 8443:8443
  volumes:
  - shibboleth-idp-credentials:/opt/shibboleth-idp/credentials:ro
  - shibboleth-idp-ext-conf:/opt/shibboleth-idp/ext-conf:ro
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=prodI-cph-02

